In [1]:
#Qno1- Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [2]:
import pandas as pd
import numpy as np

In [3]:
import numpy as np

# Create a 4x3 matrix with values from 2 to 13
matrix = np.arange(2, 14).reshape(4, 3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [5]:
#Qno2- Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [6]:
arr=np.random.randint(1,50,20).replace(
arr

array([ 5, 30, 45, 49,  1,  7, 45, 41,  4, 10,  4, 23, 11, 18, 29, 19, 12,
       22, 37, 41], dtype=int32)

In [7]:
import numpy as np

# Generate an array of 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)

print("Original Array:")
print(arr)

# Replace odd numbers with -1
arr[arr % 2 != 0] = -1
print(arr)


Original Array:
[40 38 44 23 36 20 33  6 37 33 28  9 17 20  6 12  7  7 11 31]
[40 38 44 -1 36 20 -1  6 -1 -1 28 -1 -1 20  6 12 -1 -1 -1 -1]


In [9]:
#Qno3- Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.
# a. Create a 1d-array of mobile phones prices
# b. Convert this array to float type
# c. Append a new mobile having price of 13999 Rs. to this array
# d. Reverse this array of mobile phones prices
# e. Apply GST of 18% on mobile phones prices and update this array.
# f. Sort the array in descending order of price
# g. What is the average mobile phone price
# h. What is the difference b/w maximum and minimum price

In [18]:
# a. Create a 1d-array of mobile phones prices

prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
prices

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [15]:
# b. Convert this array to float type
prices_float = prices.astype(float)
print(prices_float)

[ 6999.  7500. 11999. 27899. 14999.  9999.]


In [17]:
# c. Append a new mobile having price of 13999 Rs. to this array
prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
prices = np.append(prices, 13999)
print(prices)

[ 6999  7500 11999 27899 14999  9999 13999]


In [22]:
# d. Reverse this array of mobile phones prices
prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
reversed_prices = prices[::-1]
print(reversed_prices)

[ 9999 14999 27899 11999  7500  6999]


In [24]:
# e. Apply GST of 18% on mobile phones prices and update this array.
prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
updated_prices=(prices*18/100)+prices
print(updated_prices)

[ 8258.82  8850.   14158.82 32920.82 17698.82 11798.82]


In [27]:
# f. Sort the array in descending order of price
prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
sorted_desc = np.sort(prices)[::-1]
print(sorted_desc)

[27899 14999 11999  9999  7500  6999]


In [29]:
# g. What is the average mobile phone price
prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
average_prices=np.mean(prices)
print(average_prices)

13232.5


In [30]:
# h. What is the difference b/w maximum and minimum price
prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
min_price=np.min(prices)
max_price=np.max(prices)
diffeence_price=max_price-min_price
print(diffeence_price)

20900


In [31]:
#Qno4- Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [32]:
arr = np.array([1, 2, 0, 0, 4, 0])

non_zero_indices = np.nonzero(arr)

print("Indices of non-zero elements:", non_zero_indices[0])


Indices of non-zero elements: [0 1 4]
