In [1]:
#Qno1- Create a NumPy array containing integers from 0 to 9.

In [2]:
import numpy as np

In [5]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Qno2- Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [9]:
python_list=[10, 20, 30, 40, 50]
arr1=np.array(python_list)
arr1

array([10, 20, 30, 40, 50])

In [10]:
#Qno3- Create a 2D array (3x3) with values ranging from 0 to 8.

In [11]:
arr2=np.arange(0,9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#Qno4- Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [21]:
arr2=np.arange(0,9).reshape(3,3)
shape=arr2.shape
size = arr2.size
print(shape)
print(size)

arr3=np.random.randint(1,100,20).reshape(5,4)
arr3

(3, 3)
9


array([[61, 90, 98, 99],
       [28, 87, 50, 23],
       [32, 70, 16, 57],
       [19, 45, 37, 70],
       [33,  2, 57, 35]], dtype=int32)

In [22]:
#Qno5- Create a 3x3 array of integers and access:
# a. The second element of the first row.
# b. The third column of the 2nd row.
# c. A subarray with the first two rows and last two columns.

In [29]:
# Create a 3x3 array of integers and access:
arr3=np.arange(9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
# a. The second element of the first row.
arr3[0][1]

np.int64(1)

In [31]:
# b. The third column of the 2nd row.
arr3[1][2]

np.int64(5)

In [33]:
# c. A subarray with the first two rows and last two columns.
arr3[:2, 1:]

array([[1, 2],
       [4, 5]])

In [ ]:
#Qno6- Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [39]:
arr=np.arange(12)
print(arr)

reshape=arr.reshape(3,4)
print(reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
#Qno7- Reshape a 3x3 matrix into a 1D array.

In [44]:
arr=np.arange(9).reshape(3,3)
print(arr)
array_1d = arr.reshape(-1)
print(array_1d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [45]:
#Qno7- Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [50]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,7,2],[8,1,9]])
add=arr1+arr2
sub=arr1-arr2
mul=arr1*arr2
div=arr1/arr2
print(add)
print(sub)
print(mul)
print(div)

[[ 5  9  5]
 [12  6 15]]
[[-3 -5  1]
 [-4  4 -3]]
[[ 4 14  6]
 [32  5 54]]
[[0.25       0.28571429 1.5       ]
 [0.5        5.         0.66666667]]


In [51]:
#Qno9- Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [56]:
arr=np.arange(10)
print(arr.sum())
print(arr.mean())
print(arr.std())

45
4.5
2.8722813232690143


In [57]:
#Qno10- Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [61]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
# Method 1: Using np.dot()
C_dot = np.dot(arr1, arr2)
print(C_dot)

C_at = arr1 @ arr2
print(C_at)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [64]:
#Qno11- Find the transpose of matrix A and matrix B.

In [63]:
import numpy as np

# 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Transpose of A and B
A_T = A.T
B_T = B.T

print("Matrix A:\n", A)
print("Transpose of A:\n", A_T)

print("\nMatrix B:\n", B)
print("Transpose of B:\n", B_T)


Matrix A:
 [[1 2]
 [3 4]]
Transpose of A:
 [[1 3]
 [2 4]]

Matrix B:
 [[5 6]
 [7 8]]
Transpose of B:
 [[5 7]
 [6 8]]


In [65]:
#Qno12- Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [66]:
import numpy as np

# 3x3 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1D array with 3 elements
arr_1d = np.array([10, 20, 30])

print("2D Array:\n", arr_2d)
print("1D Array:\n", arr_1d)


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D Array:
 [10 20 30]


In [67]:
# Broadcasting addition
result = arr_2d + arr_1d

print("\nResult of 2D + 1D array:\n", result)



Result of 2D + 1D array:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [68]:
#Qno13- Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [74]:
arr=np.random.randint(0,16,16).reshape(4,4)
print(arr.max())
print(arr.min())
print(arr.mean())

15
0
5.875


In [79]:
#Qno14- Find the row-wise and column-wise sums.

In [76]:
arr = np.random.randint(0, 16,16).reshape(4, 4)

print(arr)

# Row-wise sum (sum along columns)
row_sums = np.sum(arr, axis=1)
print("\nRow-wise sums:", row_sums)

# Column-wise sum (sum along rows)
col_sums = np.sum(arr, axis=0)
print("Column-wise sums:", col_sums)

[[ 1 13 14 14]
 [13  6 14  7]
 [ 7  0 10  6]
 [11  3 13  4]]

Row-wise sums: [42 40 23 31]
Column-wise sums: [32 22 51 31]


In [78]:
#Qno15- Generate an array of 10 random integers between 1 and 50.

In [80]:
arr=np.random.randint(1,50,10)
arr

array([ 4, 29, 18, 17, 42, 24, 38, 41, 46,  6], dtype=int32)

In [81]:
#Qno16- Generate a 5x5 matrix of random floats between 0 and 1.

In [82]:
arr=np.random.rand(5,5)
arr

array([[0.02707111, 0.85317902, 0.54645532, 0.15297979, 0.04669089],
       [0.52893046, 0.99493986, 0.16147048, 0.34213969, 0.34280341],
       [0.58606522, 0.35427731, 0.72312307, 0.15273637, 0.31450068],
       [0.39266097, 0.82446996, 0.27628403, 0.97575817, 0.17388873],
       [0.59598396, 0.0206136 , 0.32674201, 0.60618018, 0.96704835]])